#!/bin/bash

# Schnuffelll Wings Installer v3.0
# @author schnuffelll

set -e

# Load Lib
GITHUB_BASE_URL="https://raw.githubusercontent.com/NinoNeoxus/schnuffelll-panel/master"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$SCRIPT_DIR/../lib.sh" ]; then
  source "$SCRIPT_DIR/../lib.sh"
elif [ -f /tmp/schnuffelll_lib.sh ]; then
  source /tmp/schnuffelll_lib.sh
else
  curl -sSL -o /tmp/schnuffelll_lib.sh "$GITHUB_BASE_URL/installer/lib.sh"
  source /tmp/schnuffelll_lib.sh
fi

# Variables
WINGS_VERSION="${WINGS_VERSION:-latest}"

install_docker() {
  output "Installing Docker..."
  
  if [ -x "$(command -v docker)" ]; then
    output "Docker already installed!"
    docker --version
  else
    curl -sSL https://get.docker.com/ | CHANNEL=stable bash
  fi
  
  systemctl enable docker
  systemctl start docker
  
  success "Docker ready!"
}

install_wings() {
  output "Installing Wings daemon..."
  
  # Create directories
  mkdir -p /etc/pterodactyl
  mkdir -p /var/lib/pterodactyl/{archives,backups,volumes}
  mkdir -p /var/run/wings
  
  # Download Wings binary
  output "Downloading Wings binary..."
  
  if [ "$WINGS_VERSION" == "latest" ]; then
    DOWNLOAD_URL="https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_amd64"
  else
    DOWNLOAD_URL="https://github.com/pterodactyl/wings/releases/download/$WINGS_VERSION/wings_linux_amd64"
  fi
  
  curl -L -o /usr/local/bin/wings "$DOWNLOAD_URL"
  chmod +x /usr/local/bin/wings
  
  output "Wings binary installed!"
  /usr/local/bin/wings --version || true
}

setup_firewall() {
  output "Configuring firewall for Wings..."
  
  # Wings ports: 8080 (API), 2022 (SFTP)
  firewall_allow_ports "8080 2022"
  
  success "Firewall configured!"
}

create_config_template() {
  output "Creating Wings config template..."
  
  if [ -f "/etc/pterodactyl/config.yml" ]; then
    output "Config already exists, skipping template creation"
    return
  fi
  
  cat > /etc/pterodactyl/config.yml <<'EOF'
# Schnuffelll Wings Configuration
# Generated by installer - CONFIGURE THIS FILE!

debug: false
uuid: REPLACE_WITH_NODE_UUID
token_id: REPLACE_WITH_TOKEN_ID
token: REPLACE_WITH_TOKEN

api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem
    key: /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem

system:
  data: /var/lib/pterodactyl/volumes
  archive_directory: /var/lib/pterodactyl/archives
  backup_directory: /var/lib/pterodactyl/backups
  sftp:
    bind_port: 2022

remote: 'https://YOUR_PANEL_URL'

# Get your configuration from the Panel:
# Admin -> Nodes -> Select Node -> Configuration Tab
EOF

  success "Config template created at /etc/pterodactyl/config.yml"
}

setup_service() {
  output "Setting up Wings systemd service..."
  
  cat > /etc/systemd/system/wings.service <<EOF
[Unit]
Description=Schnuffelll Wings Daemon
After=docker.service
Requires=docker.service
PartOf=docker.service

[Service]
User=root
WorkingDirectory=/etc/pterodactyl
LimitNOFILE=4096
PIDFile=/var/run/wings/daemon.pid
ExecStart=/usr/local/bin/wings
Restart=on-failure
StartLimitInterval=180
StartLimitBurst=30
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable wings.service
  
  success "Wings service configured!"
}

# ==================== MAIN ====================

output "╔════════════════════════════════════════╗"
output "║      SCHNUFFELLL WINGS INSTALLATION    ║"
output "╚════════════════════════════════════════╝"

install_docker
setup_firewall
install_wings
create_config_template
setup_service

echo ""
print_brake 50
success "Wings Installation Complete!"
print_brake 50
echo ""
output "Next Steps:"
output "1. Go to your Panel -> Admin -> Nodes"
output "2. Create a new node or select existing"
output "3. Go to Configuration tab"
output "4. Copy the configuration to /etc/pterodactyl/config.yml"
output "5. Start Wings: systemctl start wings"
echo ""
warning "Wings will NOT start until config.yml is properly configured!"
print_brake 50
